// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {parser} from '../models';
import {resultcollector} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PickDBFile():Promise<string>;

export function PickLogFile():Promise<string>;

export function QueryIPCounts(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<database.IPCount>>;

export function QueryStatusCounts(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<database.StatusCount>>;

export function QueryView(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<parser.LogLine>>;

export function RunImport(arg1:string,arg2:string):Promise<Array<resultcollector.Result>>;
